#' @importFrom methods setClass
#' @importFrom methods new
#' @importFrom rprojroot find_root_file
#' @importFrom rprojroot has_file
#' @importFrom yaml read_yaml
#' @importFrom httr POST
#' @importFrom httr GET
#' @importFrom httr add_headers
#' @importFrom httr content
#' @importFrom glue glue
#' @importFrom available available
#' @importFrom cli cat_rule
#' @importFrom cli cli_progress_message
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_abort
#' @importFrom cli cli_ul
#' @importFrom cli col_cyan
#' @importFrom cli cli_div
#' @importFrom cli cli_end
#' @importFrom cli cli_text
#' @importFrom cli col_grey
#' @importFrom cli pb_spin
#' @importFrom gh gh
#' @importFrom gh gh_whoami
#' @importFrom gitcreds gitcreds_get
#' @importFrom gert git_push
#' @importFrom gert git_config_global
#' @importFrom gert git_commit_all
#' @importFrom gert git_remote_list
#' @importFrom gert git_clone
#' @importFrom gert git_signature
#' @importFrom usethis proj_activate
#' @importFrom usethis git_sitrep
#' @importFrom usethis ui_yeah
#' @importFrom tools file_path_sans_ext
#' @importFrom purrr pluck
#' @importFrom purrr map_dfr
#' @importFrom tibble tibble
#' @importFrom dplyr case_when
#' @exportClass BiocBook
NULL
